ver: 6

realtime-station-id: "1C10848"

check-box:
  show-window-eew: true
  show-window-report: true
  show-window-detect: true
  show-window-rts-intensity: true
  other-auto-start: true
  update-auto-restart: true
  other-tts: true
  graphics-block-auto-zoom: false
  sound-effects-EEW: true
  sound-effects-EEW2: true
  sound-effects-PAlert: true
  sound-effects-PGA1: true
  sound-effects-PGA2: true
  sound-effects-Report: true
  sound-effects-Shindo0: true
  sound-effects-Shindo1: true
  sound-effects-Shindo2: true
  sound-effects-Update: true
