ver: 3

location-code: 711

realtime-station-id: 6732340

alert-level:
  rts-intensity: 0 # 任意即時站震度
  eew-intensity: 0 # EEW 所在地預估震度

check-box:
  show-window-eew: false
  show-window-report: false
  show-window-detect: false
  show-window-rts-intensity: false
  early-warning-trem-eew: false
  other-auto-start: false
  other-tts: false
  graphics-block-auto-zoom: false
  graphics-show-fault: false
  sound-effects-dong: false
  sound-effects-EEW: false
  sound-effects-EEW2: false
  sound-effects-PAlert: false
  sound-effects-PGA1: false
  sound-effects-PGA2: false
  sound-effects-Report: false
  sound-effects-Shindo0: false
  sound-effects-Shindo1: false
  sound-effects-Shindo2: false
  sound-effects-Update: false
