name: TREM-Lite
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: Windows
            arch: x64
            artifact-ext: exe

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build
        env:
          ELECTRON_ARCH: ${{ matrix.arch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TREM-Lite.${{ matrix.platform }}_${{ matrix.arch }}.${{ matrix.artifact-ext }}
          path: |
            ${{ github.workspace }}/dist/*.${{ matrix.artifact-ext }}
          if-no-files-found: error
