name: TREM-Lite
on:
  push:
    branches: ["main","fix_github_actions"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18]
        arch: [arm64]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build All Platforms
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TREM-Lite-Windows
          path: |
            dist/*.exe
            dist/*.msi
          if-no-files-found: error

      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TREM-Lite-macOS
          path: |
            dist/*.dmg
          if-no-files-found: error

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TREM-Lite-Linux
          path: |
            dist/*.AppImage
            dist/*.deb
          if-no-files-found: error
